{{- $name := print .Release.Name "-server" -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
spec:
  type: NodePort
  selector:
    app: {{ $name }}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
